services:
  followme:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - app/.env
    labels:
      - "traefik.http.routers.brainpdfpython.rule=Host(`followme.localhost`)"
      - "traefik.http.routers.brainpdfpython.entrypoints=web"
    networks:
      - proxy
    container_name: followme

networks:
  proxy:
    name: proxy
    external: true
