services:
  followme:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: followme
    env_file:
      - app/.env
    ports:
      - "8000:8000"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.followme.rule=Host(`followme-api.0xgaetan.dev`)"
      - "traefik.http.services.followme.loadbalancer.server.port=8000"
      - "traefik.http.routers.followme.tls.certresolver=myresolver"

networks:
  proxy:
    name: proxy
    external: true
